### ISSUE TITLE
SS14 by example pages are severely out of date

### ISSUE THREAD

**Issue by mirrorcult** [space-wizards/docs#12] opened 2023-09-21 12:41 UTC
i did a small pass over them but need to make sure they actually compile. tbh ideally we have CI for this somehow but im not sure how that would work

off the top of my head:
- needs updating for datafield auto-naming
- needs update for source gen copying (partial datadefs)
- needs update for audiosystem stuff
- needs to use soundspecifier
- needs new images that dont use eris sprites

**Comment by Jezithyr** [comment] 2024-03-04 10:16
dupe of #20

**Closed by Jezithyr** 2024-03-04 10:16 UTC
Labels: Content, Out of Date, !! IMPORTANT !!
