### ISSUE TITLE
Address the TODO OOP criticism section

### ISSUE THREAD

**Issue by AlbertSnows** [space-wizards/docs#82] opened 2023-10-17 03:10 UTC
In the ECS section we have "[TODO: finish this](https://docs.spacestation14.com/en/robust-toolbox/ecs.html#todo-finish-this)" which reflects on some challenges of implementing an OOP style code base for SS14. We should clean this section up at minimum and hopefully add additional details later.

**Comment by AlbertSnows** [comment] 2023-10-17 03:10
I have already done this, just making an issue for it. I will  create a PR and reference this issue shortly.

**Comment by Jezithyr** [comment] 2024-03-04 10:15
dupe of #15

**Closed by Jezithyr** 2024-03-04 10:15 UTC
Labels: Content, Engine, Meta, Guides/Onboarding
